export const publications = [
  {
    id: "zhou-unsupervised-2025",
    title: "Unsupervised heterogeneous group streaming feature selection",
    authors: ["Peng Zhou", "Qianzhen Chen", "Lei Sang", "Shu Zhao", "Xindong Wu"],
    venue: "Pattern Recognition",
    year: 2025,
  },
  {
    id: "sang-heterogeneous-2025",
    title: "Heterogeneous Adaptive Preference Learning for Recommendation",
    authors: ["Lei Sang", "Weichen Fei", "Yi Zhang", "Yuee Huang", "Yiwen Zhang"],
    venue: "ACM Transactions on Recommender Systems",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "sang-masked-2025",
    title: "Masked Heterogeneous Graph Attention Network for robust recommendation",
    authors: ["Lei Sang", "Xingwang Li", "Yu Wang", "Yi Zhang", "Shun Lian", "Yiwen Zhang"],
    venue: "Applied Soft Computing",
    year: 2025,
    tags: ["Security/Robustness", "Graph Learning", "Recommendation"],
  },
  {
    id: "sang-towards-2025",
    title: "Towards similar alignment and unique uniformity in collaborative filtering",
    authors: ["Lei Sang", "Yu Zhang", "Yi Zhang", "Honghao Li", "Yiwen Zhang"],
    venue: "Expert Systems with Applications",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "sang-bi-directional-2025",
    title: "Bi-Directional Transfer Graph Contrastive Learning for Social Recommendation",
    authors: ["Lei Sang", "Mingyuan Liu", "Yi Zhang", "Yuee Huang", "Yiwen Zhang"],
    venue: "IEEE Transactions on Big Data",
    year: 2025,
    tags: ["Graph Learning", "Recommendation"],
  },
  {
    id: "wang-generative-contrastive-2025",
    title: "Generative-Contrastive Heterogeneous Graph Neural Network",
    authors: ["Yu Wang", "Lei Sang", "Yi Zhang", "Yiwen Zhang", "Xindong Wu"],
    venue: "IEEE Transactions on Big Data",
    year: 2025,
    tags: ["Graph Learning"],
  },
  {
    id: "jiang-revisiting-2025",
    title: "Revisiting Alignment and Uniformity for Recommendation via Discrimination and Reliable Assessment",
    authors: ["Xinzhe Jiang", "Lei Sang", "Shun Lian", "Yi Zhang", "Yiwen Zhang"],
    venue: "IEEE Transactions on Consumer Electronics",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "sang-simple-2025",
    title: "Simple Yet Effective Heterogeneous Graph Contrastive Learning for Recommendation",
    authors: ["Lei Sang", "Haiyan Zhang", "Yu Wang", "Yiwen Zhang"],
    venue: "IEEE Transactions on Consumer Electronics",
    year: 2025,
    tags: ["Graph Learning", "Recommendation"],
  },
  {
    id: "chen-dual-domain-2025",
    title: "Dual-Domain Collaborative Denoising for Social Recommendation",
    authors: ["Wenjie Chen", "Yi Zhang", "Honghao Li", "Lei Sang", "Yiwen Zhang"],
    venue: "IEEE Transactions on Computational Social Systems",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "sang-intent-guided-2025",
    title: "Intent-Guided Heterogeneous Graph Contrastive Learning for Recommendation",
    authors: ["Lei Sang", "Yu Wang", "Yi Zhang", "Yiwen Zhang", "Xindong Wu"],
    venue: "IEEE Transactions on Knowledge and Data Engineering",
    year: 2025,
    tags: ["Graph Learning", "Recommendation"],
  },
  {
    id: "sang-adagin:-2025",
    title: "AdaGIN: Adaptive Graph Interaction Network for Click-Through Rate Prediction",
    authors: ["Lei Sang", "Honghao Li", "Yiwen Zhang", "Yi Zhang", "Yun Yang"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["Graph Learning", "CTR Prediction"],
  },
  {
    id: "li-cetn:-2025",
    title: "CETN: Contrast-enhanced Through Network for Click-Through Rate Prediction",
    authors: ["Honghao Li", "Lei Sang", "Yi Zhang", "Xuyun Zhang", "Yiwen Zhang"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["CTR Prediction"],
  },
  {
    id: "zhang-simplify-2025",
    title: "Simplify to the Limit! Embedding-Less Graph Collaborative Filtering for Recommender Systems",
    authors: ["Yi Zhang", "Yiwen Zhang", "Lei Sang", "Victor S. Sheng"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["Graph Learning", "Recommendation"],
  },
  {
    id: "sang-denoising-2025",
    title: "Denoising Heterogeneous Graph Pre-training Framework for Recommendation",
    authors: ["Lei Sang", "Yu Wang", "Yiwen Zhang", "Xindong Wu"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["Graph Learning", "Recommendation"],
  },
  {
    id: "sang-bottlenecked-2025",
    title: "Bottlenecked Heterogeneous Graph Contrastive Learning for Robust Recommendation",
    authors: ["Lei Sang", "Maohao Huang", "Yu Wang", "Yiwen Zhang", "Xindong Wu"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["Security/Robustness", "Graph Learning", "Recommendation"],
  },
  {
    id: "li-revisiting-2025",
    title: "Revisiting Feature Interactions from the Perspective of Quadratic Neural Networks for Click-through Rate Prediction",
    authors: ["Honghao Li", "Yiwen Zhang", "Yi Zhang", "Lei Sang", "Jieming Zhu"],
    venue: "Proceedings of the ACM SIGKDD International Conference on Knowledge Discovery and Data Mining (KDD) (2)",
    year: 2025,
    tags: ["CTR Prediction", "KDD"],
  },
  {
    id: "wang-intent-2025",
    title: "Intent Representation Learning with Large Language Model for Recommendation",
    authors: ["Yu Wang", "Lei Sang", "Yi Zhang", "Yiwen Zhang"],
    venue: "Proceedings of the International ACM SIGIR Conference on Research and Development in Information Retrieval (SIGIR)",
    year: 2025,
    tags: ["NLP", "Recommendation", "SIGIR"],
  },
  {
    id: "zhang-unveiling-2025",
    title: "Unveiling Contrastive Learning's Capability of Neighborhood Aggregation for Collaborative Filtering",
    authors: ["Yu Zhang", "Yiwen Zhang", "Yi Zhang", "Lei Sang", "Yun Yang"],
    venue: "Proceedings of the International ACM SIGIR Conference on Research and Development in Information Retrieval (SIGIR)",
    year: 2025,
    tags: ["Recommendation", "SIGIR"],
  },
  {
    id: "wang-intent-2025",
    title: "Intent Alignment between Interaction and Language Spaces for Recommendation",
    authors: ["Yu Wang", "Lei Sang", "Yi Zhang", "Yiwen Zhang"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "zhang-unveiling-2025",
    title: "Unveiling Contrastive Learning's Capability of Neighborhood Aggregation for Collaborative Filtering",
    authors: ["Yu Zhang", "Yiwen Zhang", "Yi Zhang", "Lei Sang", "Yun Yang"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "li-quadratic-2025",
    title: "Quadratic Interest Network for Multimodal Click-Through Rate Prediction",
    authors: ["Honghao Li", "Hanwei Li", "Jing Zhang", "Yi Zhang", "Ziniu Yu", "Lei Sang", "Yiwen Zhang"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["CTR Prediction"],
  },
  {
    id: "li-revisiting-2025",
    title: "Revisiting Feature Interactions from the Perspective of Quadratic Neural Networks for Click-through Rate Prediction",
    authors: ["Honghao Li", "Yiwen Zhang", "Yi Zhang", "Lei Sang", "Jieming Zhu"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["CTR Prediction"],
  },
  {
    id: "mu-robustness-2025",
    title: "Robustness of Prompting: Enhancing Robustness of Large Language Models Against Prompting Attacks",
    authors: ["Lin Mu", "Guowei Chu", "Li Ni", "Lei Sang", "Zhize Wu", "Peiquan Jin", "Yiwen Zhang"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["Security/Robustness", "NLP"],
  },
  {
    id: "sang-multi-view-2025",
    title: "Multi-view denoising contrastive learning for bundle recommendation",
    authors: ["Lei Sang", "Yang Hu", "Yi Zhang", "Yiwen Zhang"],
    venue: "Applied Intelligence",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "wang-privacy-preserving-2025",
    title: "A privacy-preserving framework with multi-modal data for cross-domain recommendation",
    authors: ["Li Wang", "Lei Sang", "Quangui Zhang", "Qiang Wu", "Min Xu"],
    venue: "Knowledge-Based Systems",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "li-simcen:-2025",
    title: "SimCEN: Simple Contrast-enhanced Network for CTR Prediction",
    authors: ["Honghao Li", "Lei Sang", "Yi Zhang", "Yiwen Zhang"],
    venue: "Proceedings of the ACM International Conference on Multimedia (ACM MM)",
    year: 2025,
    tags: ["CTR Prediction"],
  },
  {
    id: "zhang-exploring-2025",
    title: "Exploring the Individuality and Collectivity of Intents behind Interactions for Graph Collaborative Filtering",
    authors: ["Yi Zhang", "Lei Sang", "Yiwen Zhang"],
    venue: "Proceedings of the International ACM SIGIR Conference on Research and Development in Information Retrieval (SIGIR)",
    year: 2025,
    tags: ["Graph Learning", "Recommendation", "SIGIR"],
  },
  {
    id: "wang-privacy-preserving-2025",
    title: "A Privacy-Preserving Framework with Multi-Modal Data for Cross-Domain Recommendation",
    authors: ["Li Wang", "Lei Sang", "Quangui Zhang", "Qiang Wu", "Min Xu"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "wang-generative-contrastive-2025",
    title: "Generative-Contrastive Heterogeneous Graph Neural Network",
    authors: ["Yu Wang", "Lei Sang", "Yi Zhang", "Yiwen Zhang"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["Graph Learning"],
  },
  {
    id: "li-tf4ctr:-2025",
    title: "TF4CTR: Twin Focus Framework for CTR Prediction via Adaptive Sample Differentiation",
    authors: ["Honghao Li", "Yiwen Zhang", "Yi Zhang", "Lei Sang", "Yun Yang"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["CTR Prediction"],
  },
  {
    id: "chen-dual-domain-2025",
    title: "Dual-domain Collaborative Denoising for Social Recommendation",
    authors: ["Wenjie Chen", "Yi Zhang", "Honghao Li", "Lei Sang", "Yiwen Zhang"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "zhang-exploring-2025",
    title: "Exploring the Individuality and Collectivity of Intents behind Interactions for Graph Collaborative Filtering",
    authors: ["Yi Zhang", "Lei Sang", "Yiwen Zhang"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["Graph Learning", "Recommendation"],
  },
  {
    id: "li-dcnv3:-2025",
    title: "DCNv3: Towards Next Generation Deep Cross Network for CTR Prediction",
    authors: ["Honghao Li", "Yiwen Zhang", "Yi Zhang", "Hanwei Li", "Lei Sang"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["CTR Prediction"],
  },
  {
    id: "sang-intent-guided-2025",
    title: "Intent-guided Heterogeneous Graph Contrastive Learning for Recommendation",
    authors: ["Lei Sang", "Yu Wang", "Yi Zhang", "Yiwen Zhang", "Xindong Wu"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["Graph Learning", "Recommendation"],
  },
  {
    id: "zhang-high-order-2025",
    title: "High-Order Fusion Graph Contrastive Learning for Recommendation",
    authors: ["Yu Zhang", "Lei Sang", "Yi Zhang", "Yiwen Zhang"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["Graph Learning", "Recommendation"],
  },
  {
    id: "wang-federated-2025",
    title: "Federated Prototype-based Contrastive Learning for Privacy-Preserving Cross-domain Recommendation",
    authors: ["Li Wang", "Quangui Zhang", "Lei Sang", "Qiang Wu", "Min Xu"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "sang-feature-2025",
    title: "Feature Interaction Fusion Self-Distillation Network For CTR Prediction",
    authors: ["Lei Sang", "Qiuze Ru", "Honghao Li", "Yiwen Zhang", "Qian Cao", "Xindong Wu"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["CTR Prediction"],
  },
  {
    id: "li-ensemble-2025",
    title: "Ensemble Learning via Knowledge Transfer for CTR Prediction",
    authors: ["Honghao Li", "Yiwen Zhang", "Yi Zhang", "Lei Sang"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["CTR Prediction"],
  },
  {
    id: "sang-adversarial-2025",
    title: "Adversarial Heterogeneous Graph Neural Network for Robust Recommendation",
    authors: ["Lei Sang", "Min Xu", "Shengsheng Qian", "Xindong Wu"],
    venue: "IEEE Transactions on Computational Social Systems",
    year: 2025,
    tags: ["Security/Robustness", "Graph Learning", "Recommendation"],
  },
  {
    id: "li-cetn:-2025",
    title: "CETN: Contrast-enhanced Through Network for CTR Prediction",
    authors: ["Honghao Li", "Lei Sang", "Yi Zhang", "Xuyun Zhang", "Yiwen Zhang"],
    venue: "arXiv preprint",
    year: 2025,
    tags: ["CTR Prediction"],
  },
  {
    id: "sang-knowledge-2025",
    title: "Knowledge graph enhanced neural collaborative recommendation",
    authors: ["Lei Sang", "Min Xu", "Shengsheng Qian", "Xindong Wu"],
    venue: "Expert Systems with Applications",
    year: 2025,
    tags: ["Graph Learning", "Recommendation"],
  },
  {
    id: "sang-knowledge-2025",
    title: "Knowledge Graph enhanced Neural Collaborative Filtering with Residual Recurrent Network",
    authors: ["Lei Sang", "Min Xu", "Shengsheng Qian", "Xindong Wu"],
    venue: "Neurocomputing",
    year: 2025,
    tags: ["Graph Learning", "Recommendation"],
  },
  {
    id: "wu-noise-2025",
    title: "Noise Augmented Double-Stream Graph Convolutional Networks for Image Captioning",
    authors: ["Lingxiang Wu", "Min Xu", "Lei Sang", "Ting Yao", "Tao Mei"],
    venue: "IEEE Transactions on Circuits and Systems for Video Technology",
    year: 2025,
    tags: ["Graph Learning"],
  },
  {
    id: "sang-context-dependent-2025",
    title: "Context-Dependent Propagating-Based Video Recommendation in Multimodal Heterogeneous Information Networks",
    authors: ["Lei Sang", "Min Xu", "Shengsheng Qian", "Matt Martin", "Peter Li", "Xindong Wu"],
    venue: "IEEE Transactions on Multimedia",
    year: 2025,
    tags: ["NLP", "Recommendation"],
  },
  {
    id: "sang-multi-modal-2025",
    title: "Multi-modal multi-view Bayesian semantic embedding for community question answering",
    authors: ["Lei Sang", "Min Xu", "Shengsheng Qian", "Xindong Wu"],
    venue: "Neurocomputing",
    year: 2025,
  },
  {
    id: "sang-aaane:-2025",
    title: "AAANE: Attention-Based Adversarial Autoencoder for Multi-scale Network Embedding",
    authors: ["Lei Sang", "Min Xu", "Shengsheng Qian", "Xindong Wu"],
    venue: "PAProceedings of the ACM SIGKDD International Conference on Knowledge Discovery and Data Mining (KDD) (3)",
    year: 2025,
    tags: ["KDD"],
  },
  {
    id: "sang-aaane:-2025",
    title: "AAANE: Attention-based Adversarial Autoencoder for Multi-scale Network Embedding",
    authors: ["Lei Sang", "Min Xu", "Shengsheng Qian", "Xindong Wu"],
    venue: "arXiv preprint",
    year: 2025,
  },
  {
    id: "sang-wefest:-2025",
    title: "WEFEST: Word Embedding Feature Extension for Short Text Classification",
    authors: ["Lei Sang", "Fei Xie", "Xiaojian Liu", "Xindong Wu"],
    venue: "ICDM Workshops",
    year: 2025,
    tags: ["NLP"],
  },
];
