export const publications = [
  {
    id: "dicp-2025",
    title: "DICP: Deep In-Context Prompt for Event Causality Identification",
    authors: ["Lecheng Mu", "Jing Shen", "Li Ni", "Lei Sang", "Zongda Wu", "Pei Jin", "Yi Zhang"],
    venue: "Findings of the Association for Computational Linguistics: EMNLP 2025",
    year: 2025,
    tags: ["NLP", "Causality"],
  },
  {
    id: "unsupervised-fs-2025",
    title: "Unsupervised heterogeneous group streaming feature selection",
    authors: ["Peng Zhou", "Qian Chen", "Lei Sang", "Sheng Zhao", "Xindong Wu"],
    venue: "Pattern Recognition",
    year: 2025,
    tags: ["Feature Selection"],
  },
  {
    id: "hetero-neighborhood-2025",
    title: "Heterogeneous Neighborhood-Enhanced Graph Contrastive Learning for Recommendation",
    authors: ["Lei Sang", "Chao Zhang", "Maohao Huang", "Lecheng Mu", "Yi Zhang", "Xindong Wu"],
    venue: "IEEE Transactions on Computational Social Systems",
    year: 2025,
    tags: ["Recommendation", "Graph Learning"],
  },
  {
    id: "revisiting-feature-2025",
    title: "Revisiting Feature Interactions from the Perspective of Quadratic Neural Networks for Click-through Rate Prediction",
    authors: ["Honghao Li", "Yi Zhang", "Yi Zhang", "Lei Sang", "Jun Zhu"],
    venue: "Proceedings of the 31st ACM SIGKDD Conference on Knowledge Discovery and Data Mining",
    year: 2025,
    tags: ["CTR Prediction", "KDD"],
  },
  {
    id: "hetero-adaptive-2025",
    title: "Heterogeneous adaptive preference learning for recommendation",
    authors: ["Lei Sang", "Weichen Fei", "Yi Zhang", "Yong Huang", "Yi Zhang"],
    venue: "ACM Transactions on Recommender Systems 4 (1), 1-25",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "bottlenecked-hetero-2025",
    title: "Bottlenecked Heterogeneous Graph Contrastive Learning for Robust Recommendation",
    authors: ["Lei Sang", "Maohao Huang", "Yu Wang", "Yi Zhang", "Xindong Wu"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["Recommendation", "TOIS"],
  },
  {
    id: "masked-hetero-2025",
    title: "Masked Heterogeneous Graph Attention Network for robust recommendation",
    authors: ["Lei Sang", "X Li", "Yu Wang", "Yi Zhang", "Sheng Lian", "Yi Zhang"],
    venue: "Applied Soft Computing",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "unveiling-contrastive-2025",
    title: "Unveiling Contrastive Learning's Capability of Neighborhood Aggregation for Collaborative Filtering",
    authors: ["Yi Zhang", "Yi Zhang", "Yi Zhang", "Lei Sang", "Yan Yang"],
    venue: "Proceedings of the 48th International ACM SIGIR Conference on Research and Development in Information Retrieval",
    year: 2025,
    tags: ["Collaborative Filtering", "SIGIR"],
  },
  {
    id: "intent-llm-2025",
    title: "Intent representation learning with large language model for recommendation",
    authors: ["Yu Wang", "Lei Sang", "Yi Zhang", "Yi Zhang"],
    venue: "Proceedings of the 48th International ACM SIGIR Conference on Research and Development in Information Retrieval",
    year: 2025,
    tags: ["LLM", "Recommendation", "SIGIR"],
  },
  {
    id: "qos-llm-2025",
    title: "Quality of Service Prediction via Large Language Models",
    authors: ["Hui Liu", "Zhen Zhang", "Lei Sang", "Qing Wu", "Yi Zhang"],
    venue: "2025 IEEE International Conference on Web Services (ICWS)",
    year: 2025,
    tags: ["LLM", "Web Services"],
  },
  {
    id: "simple-hetero-2025",
    title: "Simple Yet Effective Heterogeneous Graph Contrastive Learning for Recommendation",
    authors: ["Lei Sang", "Hao Zhang", "Yu Wang", "Yi Zhang"],
    venue: "IEEE Transactions on Consumer Electronics",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "generative-contrastive-2025",
    title: "Generative-contrastive heterogeneous graph neural network",
    authors: ["Yu Wang", "Lei Sang", "Yi Zhang", "Yi Zhang", "Xindong Wu"],
    venue: "IEEE Transactions on Big Data",
    year: 2025,
    tags: ["Graph Neural Network"],
  },
  {
    id: "intent-guided-2025",
    title: "Intent-guided heterogeneous graph contrastive learning for recommendation",
    authors: ["Lei Sang", "Yu Wang", "Yi Zhang", "Yi Zhang", "Xindong Wu"],
    venue: "IEEE Transactions on Knowledge and Data Engineering",
    year: 2025,
    tags: ["Recommendation", "TKDE"],
  },
  {
    id: "dual-domain-2025",
    title: "Dual-domain collaborative denoising for social recommendation",
    authors: ["Wenjie Chen", "Yi Zhang", "Honghao Li", "Lei Sang", "Yi Zhang"],
    venue: "IEEE Transactions on Computational Social Systems",
    year: 2025,
    tags: ["Social Recommendation"],
  },
  {
    id: "revisiting-alignment-2025",
    title: "Revisiting Alignment and Uniformity for Recommendation via Discrimination and Reliable Assessment",
    authors: ["Xiaofeng Jiang", "Lei Sang", "Sheng Lian", "Yi Zhang", "Yi Zhang"],
    venue: "IEEE Transactions on Consumer Electronics",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "denoising-hetero-2025",
    title: "Denoising Heterogeneous Graph Pre-training Framework for Recommendation",
    authors: ["Lei Sang", "Yu Wang", "Yi Zhang", "Xindong Wu"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["Recommendation", "TOIS"],
  },
  {
    id: "simplify-limit-2025",
    title: "Simplify to the Limit! Embedding-less Graph Collaborative Filtering for Recommender Systems",
    authors: ["Yi Zhang", "Yi Zhang", "Lei Sang", "Victor S. Sheng"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["Collaborative Filtering", "TOIS"],
  },
  {
    id: "similar-alignment-2025",
    title: "Towards similar alignment and unique uniformity in collaborative filtering",
    authors: ["Lei Sang", "Yi Zhang", "Yi Zhang", "Honghao Li", "Yi Zhang"],
    venue: "Expert Systems with Applications 259, 125346",
    year: 2025,
    tags: ["Collaborative Filtering"],
  },
  {
    id: "cetn-2025",
    title: "CETN: Contrast-enhanced Through Network for Click-Through Rate Prediction",
    authors: ["Honghao Li", "Lei Sang", "Yi Zhang", "Xiang Zhang", "Yi Zhang"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["CTR Prediction", "TOIS"],
  },
  {
    id: "adagin-2025",
    title: "AdaGIN: Adaptive Graph Interaction Network for Click-Through Rate Prediction",
    authors: ["Lei Sang", "Honghao Li", "Yi Zhang", "Yi Zhang", "Yan Yang"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["CTR Prediction", "TOIS"],
  },
  {
    id: "multi-view-denoising-2024",
    title: "Multi-view denoising contrastive learning for bundle recommendation",
    authors: ["Lei Sang", "Yi Hu", "Yi Zhang", "Yi Zhang"],
    venue: "Applied Intelligence 54 (23), 12332-12346",
    year: 2024,
    tags: ["Recommendation"],
  },
  {
    id: "privacy-preserving-2024",
    title: "A privacy-preserving framework with multi-modal data for cross-domain recommendation",
    authors: ["Li Wang", "Lei Sang", "Qi Zhang", "Qing Wu", "Min Xu"],
    venue: "Knowledge-Based Systems 304, 112529",
    year: 2024,
    tags: ["Recommendation", "Privacy"],
  },
  {
    id: "disentanglement-enhanced-2024",
    title: "Disentanglement-Enhanced User Representation via Domain-Level Clusters for Cross-Domain Recommendation",
    authors: ["Wei Xiong", "Lei Sang", "Wei Li", "Sheng Lian", "Yi Zhang"],
    venue: "EAI International Conference on Collaborative Computing: Networking, Applications and Worksharing",
    year: 2024,
    tags: ["Recommendation"],
  },
  {
    id: "semantic-enhanced-2024",
    title: "Semantic-enhanced Heterogeneous Graph Contrastive Learning for Recommendation",
    authors: ["Lei Sang", "Fan Song", "Yu Wang", "Yi Zhang", "Yi Zhang"],
    venue: "Unknown Venue", // Missing in snippet
    year: 2024,
    tags: ["Recommendation"],
  },
  {
    id: "simcen-2024",
    title: "SimCEN: Simple Contrast-enhanced Network for CTR Prediction",
    authors: ["Honghao Li", "Lei Sang", "Yi Zhang", "Yi Zhang"],
    venue: "ACM Multimedia 2024",
    year: 2024,
    tags: ["CTR Prediction", "MM"],
  },
  {
    id: "exploring-individuality-2024",
    title: "Exploring the individuality and collectivity of intents behind interactions for graph collaborative filtering",
    authors: ["Yi Zhang", "Lei Sang", "Yi Zhang"],
    venue: "Proceedings of the 47th International ACM SIGIR Conference on Research and Development in Information Retrieval",
    year: 2024,
    tags: ["Collaborative Filtering", "SIGIR"],
  },
  {
    id: "graph-structure-learning-2024",
    title: "Graph structure learning for robust recommendation",
    authors: ["Lei Sang", "Hao Yuan", "Yong Huang", "Yi Zhang"],
    venue: "Tsinghua Science and Technology 30 (4), 1617-1635",
    year: 2024,
    tags: ["Recommendation"],
  },
  {
    id: "bi-directional-transfer-2024",
    title: "Bi-directional transfer graph contrastive learning for social recommendation",
    authors: ["Lei Sang", "Ming Liu", "Yi Zhang", "Yong Huang", "Yi Zhang"],
    venue: "IEEE Transactions on Big Data",
    year: 2024,
    tags: ["Social Recommendation"],
  },
  {
    id: "adversarial-hetero-2023",
    title: "Adversarial heterogeneous graph neural network for robust recommendation",
    authors: ["Lei Sang", "Min Xu", "Shengsheng Qian", "Xindong Wu"],
    venue: "IEEE Transactions on Computational Social Systems 10 (5), 2660-2671",
    year: 2023,
    tags: ["Recommendation"],
  },
  {
    id: "kg-enhanced-ncf-2021",
    title: "Knowledge graph enhanced neural collaborative filtering with residual recurrent network",
    authors: ["Lei Sang", "Min Xu", "Shengsheng Qian", "Xindong Wu"],
    venue: "Neurocomputing 454, 417-429",
    year: 2021,
    tags: ["Recommendation", "Knowledge Graph"],
  },
  {
    id: "kg-enhanced-ncr-2021",
    title: "Knowledge graph enhanced neural collaborative recommendation",
    authors: ["Lei Sang", "Min Xu", "Shengsheng Qian", "Xindong Wu"],
    venue: "Expert systems with applications 164, 113992",
    year: 2021,
    tags: ["Recommendation", "Knowledge Graph"],
  },
  {
    id: "noise-augmented-2020",
    title: "Noise augmented double-stream graph convolutional networks for image captioning",
    authors: ["Le Wu", "Min Xu", "Lei Sang", "Ting Yao", "Tao Mei"],
    venue: "IEEE Transactions on Circuits and Systems for Video Technology 31 (8), 3118-3127",
    year: 2020,
    tags: ["Image Captioning"],
  },
  {
    id: "neural-collab-kg-2020",
    title: "Neural collaborative recommendation with knowledge graph",
    authors: ["Lei Sang", "Lin Li"],
    venue: "2020 IEEE International Conference on Knowledge Graph (ICKG), 203-210",
    year: 2020,
    tags: ["Recommendation", "Knowledge Graph"],
  },
  {
    id: "context-dependent-2020",
    title: "Context-dependent propagating-based video recommendation in multimodal heterogeneous information networks",
    authors: ["Lei Sang", "Min Xu", "Shengsheng Qian", "M. Martin", "Pan Li", "Xindong Wu"],
    venue: "IEEE Transactions on Multimedia 23, 2019-2032",
    year: 2020,
    tags: ["Video Recommendation"],
  },
  {
    id: "graph-rep-learning-2020",
    title: "Graph Representation Learning-Based Recommender Systems",
    authors: ["Lei Sang"],
    venue: "PQDT-Global",
    year: 2020,
    tags: ["Recommendation"],
  },
  {
    id: "multi-modal-qa-2019",
    title: "Multi-modal multi-view Bayesian semantic embedding for community question answering",
    authors: ["Lei Sang", "Min Xu", "Shengsheng Qian", "Xindong Wu"],
    venue: "Neurocomputing 334, 44-58",
    year: 2019,
    tags: ["Question Answering"],
  },
  {
    id: "aaane-2019",
    title: "AAANE: Attention-based adversarial autoencoder for multi-scale network embedding",
    authors: ["Lei Sang", "Min Xu", "Shengsheng Qian", "Xindong Wu"],
    venue: "Pacific-Asia Conference on Knowledge Discovery and Data Mining, 3-14",
    year: 2019,
    tags: ["Network Embedding"],
  },
  {
    id: "wefest-2016",
    title: "WEFEST: word embedding feature extension for short text classification",
    authors: ["Lei Sang", "Fei Xie", "Xue Liu", "Xindong Wu"],
    venue: "2016 IEEE 16th International Conference on Data Mining Workshops (ICDMW)",
    year: 2016,
    tags: ["Text Classification"],
  }
];
