export const publications = [
  {
    id: "dicp-2025",
    title: "DICP: Deep In-Context Prompt for Event Causality Identification",
    authors: ["L Mu", "J Shen", "L Ni", "L Sang", "Z Wu", "P Jin", "Y Zhang"],
    venue: "Findings of the Association for Computational Linguistics: EMNLP 2025",
    year: 2025,
    tags: ["NLP", "Causality"],
  },
  {
    id: "unsupervised-fs-2025",
    title: "Unsupervised heterogeneous group streaming feature selection",
    authors: ["P Zhou", "Q Chen", "L Sang", "S Zhao", "X Wu"],
    venue: "Pattern Recognition",
    year: 2025,
    tags: ["Feature Selection"],
  },
  {
    id: "hetero-neighborhood-2025",
    title: "Heterogeneous Neighborhood-Enhanced Graph Contrastive Learning for Recommendation",
    authors: ["L Sang", "C Zhang", "M Huang", "L Mu", "Y Zhang", "X Wu"],
    venue: "IEEE Transactions on Computational Social Systems",
    year: 2025,
    tags: ["Recommendation", "Graph Learning"],
  },
  {
    id: "revisiting-feature-2025",
    title: "Revisiting Feature Interactions from the Perspective of Quadratic Neural Networks for Click-through Rate Prediction",
    authors: ["H Li", "Y Zhang", "Y Zhang", "L Sang", "J Zhu"],
    venue: "Proceedings of the 31st ACM SIGKDD Conference on Knowledge Discovery and Data Mining",
    year: 2025,
    tags: ["CTR Prediction", "KDD"],
  },
  {
    id: "hetero-adaptive-2025",
    title: "Heterogeneous adaptive preference learning for recommendation",
    authors: ["L Sang", "W Fei", "Y Zhang", "Y Huang", "Y Zhang"],
    venue: "ACM Transactions on Recommender Systems 4 (1), 1-25",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "bottlenecked-hetero-2025",
    title: "Bottlenecked Heterogeneous Graph Contrastive Learning for Robust Recommendation",
    authors: ["L Sang", "M Huang", "Y Wang", "Y Zhang", "X Wu"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["Recommendation", "TOIS"],
  },
  {
    id: "masked-hetero-2025",
    title: "Masked Heterogeneous Graph Attention Network for robust recommendation",
    authors: ["L Sang", "X Li", "Y Wang", "Y Zhang", "S Lian", "Y Zhang"],
    venue: "Applied Soft Computing",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "unveiling-contrastive-2025",
    title: "Unveiling Contrastive Learning's Capability of Neighborhood Aggregation for Collaborative Filtering",
    authors: ["Y Zhang", "Y Zhang", "Y Zhang", "L Sang", "Y Yang"],
    venue: "Proceedings of the 48th International ACM SIGIR Conference on Research and Development in Information Retrieval",
    year: 2025,
    tags: ["Collaborative Filtering", "SIGIR"],
  },
  {
    id: "intent-llm-2025",
    title: "Intent representation learning with large language model for recommendation",
    authors: ["Y Wang", "L Sang", "Y Zhang", "Y Zhang"],
    venue: "Proceedings of the 48th International ACM SIGIR Conference on Research and Development in Information Retrieval",
    year: 2025,
    tags: ["LLM", "Recommendation", "SIGIR"],
  },
  {
    id: "qos-llm-2025",
    title: "Quality of Service Prediction via Large Language Models",
    authors: ["H Liu", "Z Zhang", "L Sang", "Q Wu", "Y Zhang"],
    venue: "2025 IEEE International Conference on Web Services (ICWS)",
    year: 2025,
    tags: ["LLM", "Web Services"],
  },
  {
    id: "robustness-prompting-2025",
    title: "Robustness of Prompting: Enhancing Robustness of Large Language Models Against Prompting Attacks",
    authors: ["L Mu", "G Chu", "L Ni", "L Sang", "Z Wu", "P Jin", "Y Zhang"],
    venue: "arXiv preprint arXiv:2506.03627",
    year: 2025,
    tags: ["LLM", "Security"],
  },
  {
    id: "hetero-masked-contrastive-2025",
    title: "Heterogeneous Graph Masked Contrastive Learning for Robust Recommendation",
    authors: ["L Sang", "Y Wang", "Y Zhang"],
    venue: "arXiv preprint arXiv:2505.24172",
    year: 2025,
    tags: ["Recommendation", "Graph Learning"],
  },
  {
    id: "simple-hetero-2025",
    title: "Simple Yet Effective Heterogeneous Graph Contrastive Learning for Recommendation",
    authors: ["L Sang", "H Zhang", "Y Wang", "Y Zhang"],
    venue: "IEEE Transactions on Consumer Electronics",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "generative-contrastive-2025",
    title: "Generative-contrastive heterogeneous graph neural network",
    authors: ["Y Wang", "L Sang", "Y Zhang", "Y Zhang", "X Wu"],
    venue: "IEEE Transactions on Big Data",
    year: 2025,
    tags: ["Graph Neural Network"],
  },
  {
    id: "quadratic-interest-2025",
    title: "Quadratic Interest Network for Multimodal Click-Through Rate Prediction",
    authors: ["H Li", "H Li", "J Zhang", "Y Zhang", "Z Yu", "L Sang", "Y Zhang"],
    venue: "arXiv preprint arXiv:2504.17699",
    year: 2025,
    tags: ["CTR Prediction", "Multimodal"],
  },
  {
    id: "intent-guided-2025",
    title: "Intent-guided heterogeneous graph contrastive learning for recommendation",
    authors: ["L Sang", "Y Wang", "Y Zhang", "Y Zhang", "X Wu"],
    venue: "IEEE Transactions on Knowledge and Data Engineering",
    year: 2025,
    tags: ["Recommendation", "TKDE"],
  },
  {
    id: "dual-domain-2025",
    title: "Dual-domain collaborative denoising for social recommendation",
    authors: ["W Chen", "Y Zhang", "H Li", "L Sang", "Y Zhang"],
    venue: "IEEE Transactions on Computational Social Systems",
    year: 2025,
    tags: ["Social Recommendation"],
  },
  {
    id: "revisiting-alignment-2025",
    title: "Revisiting Alignment and Uniformity for Recommendation via Discrimination and Reliable Assessment",
    authors: ["X Jiang", "L Sang", "S Lian", "Y Zhang", "Y Zhang"],
    venue: "IEEE Transactions on Consumer Electronics",
    year: 2025,
    tags: ["Recommendation"],
  },
  {
    id: "denoising-hetero-2025",
    title: "Denoising Heterogeneous Graph Pre-training Framework for Recommendation",
    authors: ["L Sang", "Y Wang", "Y Zhang", "X Wu"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["Recommendation", "TOIS"],
  },
  {
    id: "simplify-limit-2025",
    title: "Simplify to the Limit! Embedding-less Graph Collaborative Filtering for Recommender Systems",
    authors: ["Y Zhang", "Y Zhang", "L Sang", "VS Sheng"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["Collaborative Filtering", "TOIS"],
  },
];

// Page 2 (21-50)
publications.push(
  {
    id: "similar-alignment-2025",
    title: "Towards similar alignment and unique uniformity in collaborative filtering",
    authors: ["L Sang", "Y Zhang", "Y Zhang", "H Li", "Y Zhang"],
    venue: "Expert Systems with Applications 259, 125346",
    year: 2025,
    tags: ["Collaborative Filtering"],
  },
  {
    id: "cetn-2025",
    title: "CETN: Contrast-enhanced Through Network for Click-Through Rate Prediction",
    authors: ["H Li", "L Sang", "Y Zhang", "X Zhang", "Y Zhang"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["CTR Prediction", "TOIS"],
  },
  {
    id: "adagin-2025",
    title: "AdaGIN: Adaptive Graph Interaction Network for Click-Through Rate Prediction",
    authors: ["L Sang", "H Li", "Y Zhang", "Y Zhang", "Y Yang"],
    venue: "ACM Transactions on Information Systems",
    year: 2025,
    tags: ["CTR Prediction", "TOIS"],
  },
  {
    id: "multi-view-denoising-2024",
    title: "Multi-view denoising contrastive learning for bundle recommendation",
    authors: ["L Sang", "Y Hu", "Y Zhang", "Y Zhang"],
    venue: "Applied Intelligence 54 (23), 12332-12346",
    year: 2024,
    tags: ["Recommendation"],
  },
  {
    id: "ensemble-learning-2024",
    title: "Ensemble Learning via Knowledge Transfer for CTR Prediction",
    authors: ["H Li", "Y Zhang", "Y Zhang", "L Sang"],
    venue: "arXiv preprint arXiv:2411.16122",
    year: 2024,
    tags: ["CTR Prediction"],
  },
  {
    id: "privacy-preserving-2024",
    title: "A privacy-preserving framework with multi-modal data for cross-domain recommendation",
    authors: ["L Wang", "L Sang", "Q Zhang", "Q Wu", "M Xu"],
    venue: "Knowledge-Based Systems 304, 112529",
    year: 2024,
    tags: ["Recommendation", "Privacy"],
  },
  {
    id: "disentanglement-enhanced-2024",
    title: "Disentanglement-Enhanced User Representation via Domain-Level Clusters for Cross-Domain Recommendation",
    authors: ["W Xiong", "L Sang", "W Li", "S Lian", "Y Zhang"],
    venue: "EAI International Conference on Collaborative Computing: Networking, Applications and Worksharing",
    year: 2024,
    tags: ["Recommendation"],
  },
  {
    id: "feature-interaction-fusion-2024",
    title: "Feature Interaction Fusion Self-Distillation Network For CTR Prediction",
    authors: ["L Sang", "Q Ru", "H Li", "Y Zhang", "Q Cao", "X Wu"],
    venue: "arXiv preprint arXiv:2411.07508",
    year: 2024,
    tags: ["CTR Prediction"],
  },
  {
    id: "semantic-enhanced-2024",
    title: "Semantic-enhanced Heterogeneous Graph Contrastive Learning for Recommendation",
    authors: ["L Sang", "F Song", "Y Wang", "Y Zhang", "Y Zhang"],
    venue: "Unknown Venue", // Missing in snippet
    year: 2024,
    tags: ["Recommendation"],
  },
  {
    id: "federated-prototype-2024",
    title: "Federated prototype-based contrastive learning for privacy-preserving cross-domain recommendation",
    authors: ["L Wang", "Q Zhang", "L Sang", "Q Wu", "M Xu"],
    venue: "arXiv e-prints, arXiv: 2409.03294",
    year: 2024,
    tags: ["Recommendation", "Federated Learning"],
  },
  {
    id: "simcen-2024",
    title: "SimCEN: Simple Contrast-enhanced Network for CTR Prediction",
    authors: ["H Li", "L Sang", "Y Zhang", "Y Zhang"],
    venue: "ACM Multimedia 2024",
    year: 2024,
    tags: ["CTR Prediction", "MM"],
  },
  {
    id: "fusion-self-supervised-2024",
    title: "Fusion Self-supervised Learning for Recommendation",
    authors: ["Y Zhang", "L Sang", "Y Zhang", "Y Zhang", "Y Yang"],
    venue: "arXiv preprint arXiv:2407.19692",
    year: 2024,
    tags: ["Recommendation"],
  },
  {
    id: "fcn-2024",
    title: "FCN: Fusing Exponential and Linear Cross Network for Click-Through Rate Prediction",
    authors: ["H Li", "Y Zhang", "Y Zhang", "H Li", "L Sang", "J Zhu"],
    venue: "arXiv preprint arXiv:2407.13349",
    year: 2024,
    tags: ["CTR Prediction"],
  },
  {
    id: "exploring-individuality-2024",
    title: "Exploring the individuality and collectivity of intents behind interactions for graph collaborative filtering",
    authors: ["Y Zhang", "L Sang", "Y Zhang"],
    venue: "Proceedings of the 47th International ACM SIGIR Conference on Research and Development in Information Retrieval",
    year: 2024,
    tags: ["Collaborative Filtering", "SIGIR"],
  },
  {
    id: "high-order-fusion-2024",
    title: "High-order fusion graph contrastive learning for recommendation",
    authors: ["Y Zhang", "L Sang", "Y Zhang", "Y Zhang"],
    venue: "arXiv e-prints, arXiv: 2407.19692",
    year: 2024,
    tags: ["Recommendation"],
  },
  {
    id: "dcnv3-2024",
    title: "Dcnv3: Towards next generation deep cross network for ctr prediction",
    authors: ["H Li", "Y Zhang", "Y Zhang", "H Li", "L Sang"],
    venue: "arXiv e-prints, arXiv: 2407.13349",
    year: 2024,
    tags: ["CTR Prediction"],
  },
  {
    id: "graph-structure-learning-2024",
    title: "Graph structure learning for robust recommendation",
    authors: ["L Sang", "H Yuan", "Y Huang", "Y Zhang"],
    venue: "Tsinghua Science and Technology 30 (4), 1617-1635",
    year: 2024,
    tags: ["Recommendation"],
  },
  {
    id: "tf4ctr-2024",
    title: "TF4CTR: twin focus framework for CTR prediction via adaptive sample differentiation",
    authors: ["H Li", "Y Zhang", "Y Zhang", "L Sang", "Y Yang"],
    venue: "arXiv preprint arXiv:2405.03167",
    year: 2024,
    tags: ["CTR Prediction"],
  },
  {
    id: "bi-directional-transfer-2024",
    title: "Bi-directional transfer graph contrastive learning for social recommendation",
    authors: ["L Sang", "M Liu", "Y Zhang", "Y Huang", "Y Zhang"],
    venue: "IEEE Transactions on Big Data",
    year: 2024,
    tags: ["Social Recommendation"],
  },
  {
    id: "cetn-arxiv-2023",
    title: "CETN: contrast-enhanced through network for CTR prediction",
    authors: ["H Li", "L Sang", "Y Zhang", "X Zhang", "Y Zhang"],
    venue: "arXiv preprint arXiv:2312.09715",
    year: 2023,
    tags: ["CTR Prediction"],
  },
  {
    id: "adversarial-hetero-2023",
    title: "Adversarial heterogeneous graph neural network for robust recommendation",
    authors: ["L Sang", "M Xu", "S Qian", "X Wu"],
    venue: "IEEE Transactions on Computational Social Systems 10 (5), 2660-2671",
    year: 2023,
    tags: ["Recommendation"],
  },
  {
    id: "kg-enhanced-ncf-2021",
    title: "Knowledge graph enhanced neural collaborative filtering with residual recurrent network",
    authors: ["L Sang", "M Xu", "S Qian", "X Wu"],
    venue: "Neurocomputing 454, 417-429",
    year: 2021,
    tags: ["Recommendation", "Knowledge Graph"],
  },
  {
    id: "kg-enhanced-ncr-2021",
    title: "Knowledge graph enhanced neural collaborative recommendation",
    authors: ["L Sang", "M Xu", "S Qian", "X Wu"],
    venue: "Expert systems with applications 164, 113992",
    year: 2021,
    tags: ["Recommendation", "Knowledge Graph"],
  },
  {
    id: "noise-augmented-2020",
    title: "Noise augmented double-stream graph convolutional networks for image captioning",
    authors: ["L Wu", "M Xu", "L Sang", "T Yao", "T Mei"],
    venue: "IEEE Transactions on Circuits and Systems for Video Technology 31 (8), 3118-3127",
    year: 2020,
    tags: ["Image Captioning"],
  },
  {
    id: "neural-collab-kg-2020",
    title: "Neural collaborative recommendation with knowledge graph",
    authors: ["L Sang", "L Li"],
    venue: "2020 IEEE International Conference on Knowledge Graph (ICKG), 203-210",
    year: 2020,
    tags: ["Recommendation", "Knowledge Graph"],
  },
  {
    id: "context-dependent-2020",
    title: "Context-dependent propagating-based video recommendation in multimodal heterogeneous information networks",
    authors: ["L Sang", "M Xu", "S Qian", "M Martin", "P Li", "X Wu"],
    venue: "IEEE Transactions on Multimedia 23, 2019-2032",
    year: 2020,
    tags: ["Video Recommendation"],
  },
  {
    id: "graph-rep-learning-2020",
    title: "Graph Representation Learning-Based Recommender Systems",
    authors: ["L Sang"],
    venue: "PQDT-Global",
    year: 2020,
    tags: ["Recommendation"],
  },
  {
    id: "multi-modal-qa-2019",
    title: "Multi-modal multi-view Bayesian semantic embedding for community question answering",
    authors: ["L Sang", "M Xu", "SS Qian", "X Wu"],
    venue: "Neurocomputing 334, 44-58",
    year: 2019,
    tags: ["Question Answering"],
  },
  {
    id: "aaane-2019",
    title: "AAANE: Attention-based adversarial autoencoder for multi-scale network embedding",
    authors: ["L Sang", "M Xu", "S Qian", "X Wu"],
    venue: "Pacific-Asia Conference on Knowledge Discovery and Data Mining, 3-14",
    year: 2019,
    tags: ["Network Embedding"],
  },
  {
    id: "wefest-2016",
    title: "WEFEST: word embedding feature extension for short text classification",
    authors: ["L Sang", "F Xie", "X Liu", "X Wu"],
    venue: "2016 IEEE 16th International Conference on Data Mining Workshops (ICDMW)",
    year: 2016,
    tags: ["Text Classification"],
  },
);
